# Generated by Django 4.1.1 on 2022-09-06 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_steps', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'db_table': 'games',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(unique=True)),
                ('visits', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'db_table': 'pages',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('steps', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserGame',
                'verbose_name_plural': 'UserGames',
                'db_table': 'user_games',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='GameProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.page')),
                ('userGame', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='game.usergame')),
            ],
            options={
                'verbose_name': 'Game Progress',
                'verbose_name_plural': 'Game Progresses',
                'db_table': 'game_progresses',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='end_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='endPage', to='game.page'),
        ),
        migrations.AddField(
            model_name='game',
            name='start_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='startPage', to='game.page'),
        ),
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gameType', to='info.gametype'),
        ),
    ]
